version: '3.1'

services:

  # Use root/root as user/password credentials
  db:
    image: mysql:8.0.27
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql/mysql-dump:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commenter
    ports:
      - "3306:3306"

  # Uses root/root as user/password credentials
  phpmyadmin:
    image: phpmyadmin:5.1.1-apache
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - db
    links:
      - db

volumes:
  mysql-volume: